import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#3f0300",
        "on-tertiary-container": "#152f5c",
        "inverse-primary": "#785915",
        "on-primary-container": "#412d00",
        "on-primary-fixed-variant": "#5d4200",
        "surface-bright": "#3c3936",
        "inverse-on-surface": "#33302d",
        "secondary": "#C13B25",
        "outline": "#9a8f7f",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary-container": "#8198cb",
        "surface-tint": "#B8934A",
        "on-surface-variant": "#C8BFB0",
        "primary": "#B8934A",
        "surface-dim": "#080603",
        "surface-variant": "#2A2218",
        "surface": "#0D0B09",
        "background": "#0D0B09",
        "on-tertiary-fixed-variant": "#2e4674",
        "surface-container-highest": "#302618",
        "primary-container": "#8a6a2e",
        "on-secondary-container": "#ff9f8d",
        "on-primary-fixed": "#261900",
        "on-secondary": "#F5F0E8",
        "inverse-surface": "#e8e1dd",
        "secondary-fixed-dim": "#ffb4a6",
        "tertiary": "#afc6fc",
        "secondary-container": "#C13B25",
        "primary-fixed": "#ffdea4",
        "on-tertiary-fixed": "#001a42",
        "surface-container-low": "#161009",
        "primary-fixed-dim": "#B8934A",
        "surface-container-high": "#241C10",
        "surface-container": "#1A140C",
        "on-error-container": "#ffdad6",
        "on-background": "#E8E0D4",
        "on-surface": "#E8E0D4",
        "secondary-fixed": "#ffdad3",
        "error": "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "3rem",
        "section-padding-mobile": "3.75rem",
        gutter: "1.5rem",
        "stack-md": "1.5rem",
        "stack-sm": "0.5rem",
        "section-padding": "5rem",
      },
      fontFamily: {
        "display-lg": ["var(--font-bebas)"],
        "label-caps": ["var(--font-space)"],
        "headline-lg-mobile": ["var(--font-bebas)"],
        "label-md": ["var(--font-space)"],
        "headline-lg": ["var(--font-bebas)"],
        "body-lg": ["var(--font-garamond)"],
        "headline-xl": ["var(--font-bebas)"],
        "body-md": ["var(--font-garamond)"],
      },
      fontSize: {
        "display-lg": [
          "120px",
          {
            lineHeight: "100%",
            letterSpacing: "-0.02em",
            fontWeight: "400",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "120%",
            letterSpacing: "0.2em",
            fontWeight: "700",
          },
        ],
        "headline-lg-mobile": [
          "36px",
          { lineHeight: "110%", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "140%", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "110%",
            letterSpacing: "0.05em",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "22px",
          { lineHeight: "150%", fontWeight: "400" },
        ],
        "headline-xl": [
          "80px",
          {
            lineHeight: "100%",
            letterSpacing: "0.02em",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "18px",
          { lineHeight: "160%", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
